GET {{service}}/v1/info
Content-Type: application/json
X-UserID: 1

{
}

###

GET {{service}}/v1/report
Content-Type: application/json
X-UserID: 1

###

POST {{service}}/v1/create
Content-Type: application/json
X-UserID: 1

{}

###