// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"gitlab.com/oke11o/walletsuro/internal/generated/restapi/operations/wallet"
	"gitlab.com/oke11o/walletsuro/internal/handler"
	"log"
	"os"

	"github.com/go-openapi/loads"
	flags "github.com/jessevdk/go-flags"

	"gitlab.com/oke11o/walletsuro/internal/generated/restapi"
	"gitlab.com/oke11o/walletsuro/internal/generated/restapi/operations"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {

	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	s := handler.NewServer()

	api := operations.NewWalletsuroAPI(swaggerSpec)
	handlers(api, s)

	server := restapi.NewServer(api)
	defer server.Shutdown()

	parser := flags.NewParser(server, flags.Default)
	parser.ShortDescription = "Swagger Walletsuro"
	parser.LongDescription = swaggerSpec.Spec().Info.Description
	server.ConfigureFlags()
	for _, optsGroup := range api.CommandLineOptionsGroups {
		_, err := parser.AddGroup(optsGroup.ShortDescription, optsGroup.LongDescription, optsGroup.Options)
		if err != nil {
			log.Fatalln(err)
		}
	}

	if _, err := parser.Parse(); err != nil {
		code := 1
		if fe, ok := err.(*flags.Error); ok {
			if fe.Type == flags.ErrHelp {
				code = 0
			}
		}
		os.Exit(code)
	}

	server.ConfigureAPI()

	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}

func handlers(api *operations.WalletsuroAPI, s *handler.Server) {
	api.WalletInfoHandler = wallet.InfoHandlerFunc(s.Info)
}
